version: '3.8'

services:
  checkhouse:
    image: nickolback/checkhouse:latest
    container_name: checkhouse_app
    ports:
      - "5000:5000"
    volumes:
      - ./dados:/app/dados
    restart: unless-stopped